development:
  sessions:
    default:
      database: pitchdork-dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: pitchdork-test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true